name: "Web Components Code Quality"
description:
  "This action is designed to format and test Web Component repositories on pull
  requests. It helps ensure that your code meets the required quality standards."
author: "Zebra Technologies"

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: compass
  color: "blue"

# Define your inputs here.
inputs:
  token:
    description: "Token used for pushing fixes and commenting on PRs"
    required: true

  working-directory:
    description: "The working directory"
    required: false
    default: "."

  web-components-src:
    description: "The path to the directory containing the web components source code"
    required: false
    default: "src/**/*.{ts,tsx}"

  test-src:
    description: "The path to the directory containing the test source code"
    required: false
    default: "src/test/**/*.test.ts"

  test-results-path:
    description: "The path to the test results file"
    required: false
    default: "./test-results.xml"

  coverage-path:
    description: "The path to the coverage file"
    required: false
    default: "coverage/lcov.info"

  run-static-analysis:
    description: "Whether to run static analysis"
    required: false
    default: "true"

  run-code-formatting:
    description: "Whether to run code formatting"
    required: false
    default: "true"

  run-tests:
    description: "Whether to run tests"
    required: false
    default: "true"

  run-coverage:
    description: "Whether to run coverage"
    required: false
    default: "true"

  create-comment:
    description: "Whether to create a comment on the PR"
    required: false
    default: "true"

  coverage-pass-score:
    description: "The minimum coverage score required to pass"
    required: false
    default: "80"

  eslint-config-path:
    description: "The path to the ESLint configuration file"
    required: false
    default: "eslint.config.*"

  test-config-path:
    description: "The path to the test configuration file"
    required: false
    default: "web-test-runner.config.*"

  eslint-cmd:
    description: "The command to run ESLint"
    required: false
    default: ""
runs:
  using: node20
  main: dist/index.js
